### ISSUE TITLE
Separate JavaScript libraries from in-house code.

### ISSUE THREAD

**Issue by kostasx** [MaryRichelle/Books-library#1]
It is recommended that you create a `lib/` folder inside the `js/` folder and place all the library, third-party code in there and keep them separated from the team's code.

```
js/
  app.js
  book.js
  lib/bubble/bubble.min.js
  lib/bubble/bubble.min.css
  lib/jquery/jquery.js
  lib/jquery/jquery.min.js
```

You can even separate your code into different files and modules, to keep things organized and avoid git conflicts when working on the functionality of the app.

**Same rule** also applies on third-party CSS code.

**Comment by MaryRichelle** [comment]
Thank you for the suggestion. will do that

**Comment by kostasx** [comment]
The issue is closed but the structure is still the same. There is no way to distinguish the third-party code (should be in a /lib/ folder) from the in-house (team) code. @MaryRichelle

**Comment by MaryRichelle** [comment]
Done. needed to push the changes. Thanks
