### ISSUE TITLE
Add Members section

### ISSUE THREAD

**Issue by kostasx** [MaryRichelle/Books-library#2]
For example:

```markdown

## Developer Team

- **Ada Lovelace**: Programmer
- **Charles Babbage**: Engineer
- **Alan Turin**: AI-expert
```

**Comment by kostasx** [comment]
This Issue should re-open, and close only when the task is finished. @MaryRichelle

**Comment by MaryRichelle** [comment]
I agree and Thank you for taking look into this but we planned to add members in new repository this is demo for our project.
